//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoDetalle
    {
        public long IdCodigoDocumentoDetalle { get; set; }
        public long IdCodigoDocumento { get; set; }
        public string IdHelm { get; set; }
        public string NombreArticulo { get; set; }
        public Nullable<int> ItemDetalle { get; set; }
        public string NombreUnidadMedida { get; set; }
        public string SiglaUnidadMedida { get; set; }
        public string UnidadMedidaSunat { get; set; }
        public string TipoProducto { get; set; }
        public string CodigoProducto { get; set; }
        public string TipoConcepto { get; set; }
        public string CodigoConcepto { get; set; }
        public string CuentaContableProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<byte> TipoPrecio { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public string CodigoArticulo { get; set; }
        public Nullable<bool> EsDescuento { get; set; }
        public Nullable<decimal> MontoISC { get; set; }
        public Nullable<decimal> TasaISC { get; set; }
        public Nullable<decimal> MontoBruto { get; set; }
        public Nullable<decimal> MontoIGV { get; set; }
        public Nullable<byte> TipoISC { get; set; }
        public Nullable<decimal> PorcentajePercepcionArticulo { get; set; }
        public Nullable<decimal> MontoMinimoConsumidorFinal { get; set; }
        public Nullable<byte> TipoPercepcion { get; set; }
        public Nullable<decimal> PorcentajePercepcionVenta { get; set; }
        public Nullable<decimal> ImportePercepcion { get; set; }
    
        public virtual Documento Documento { get; set; }
    }
}
