//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento()
        {
            this.DocumentoDetalle = new HashSet<DocumentoDetalle>();
        }
    
        public long IdCodigoDocumento { get; set; }
        public string IdHelm { get; set; }
        public Nullable<int> CodigoDocumento { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<int> CodigoDocumentoCliente { get; set; }
        public string NumeroDocumentoCliente { get; set; }
        public string DireccionCliente { get; set; }
        public string NombreSolidario { get; set; }
        public string NombreNave { get; set; }
        public Nullable<decimal> TRB { get; set; }
        public Nullable<decimal> Eslora { get; set; }
        public Nullable<int> CodigoMoneda { get; set; }
        public string NombreMotivoNC_ND { get; set; }
        public string CodigoSunatNC_ND { get; set; }
        public string Serie { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public string Glosa { get; set; }
        public string FormaPago { get; set; }
        public string Observaciones { get; set; }
        public bool Estado { get; set; }
        public string SerieReferencia { get; set; }
        public string NumeroReferencia { get; set; }
        public Nullable<int> CodigoDocumentoReferencia { get; set; }
        public Nullable<decimal> MontoISC { get; set; }
        public Nullable<decimal> MontoIGV { get; set; }
        public Nullable<decimal> DescuentoGlobal { get; set; }
        public Nullable<decimal> MontoAfecto { get; set; }
        public Nullable<decimal> MontoInafecto { get; set; }
        public Nullable<decimal> MontoExonerado { get; set; }
        public Nullable<decimal> MontoRegalo { get; set; }
        public Nullable<decimal> MontoDonacion { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<byte> TipoVenta { get; set; }
        public Nullable<decimal> TotalDescuento { get; set; }
        public Nullable<byte> TipoIGV { get; set; }
        public string SerieReferencia2 { get; set; }
        public string NumeroReferencia2 { get; set; }
        public Nullable<int> CodigoDocumentoReferencia2 { get; set; }
        public Nullable<byte> ClienteConsumidorFinal { get; set; }
        public Nullable<byte> TipoAgenteTributario { get; set; }
        public Nullable<decimal> ImportePercepcion { get; set; }
        public string OrdenCompra { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string EmailCliente { get; set; }
        public Nullable<byte> TrasladoContabilidad { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaHoraCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaHoraActualizacion { get; set; }
        public string CodigoDetraccion { get; set; }
        public Nullable<decimal> PorcentajeDetraccion { get; set; }
        public string GlosaDetraccion { get; set; }
        public bool FlagSunat { get; set; }
        public bool FlagFE { get; set; }
        public string CodigoSunat { get; set; }
        public string EnvioXML { get; set; }
        public string RespuestaXML { get; set; }
        public string ArchivoPDF { get; set; }
        public string Mensaje { get; set; }
        public string EstadoSunat { get; set; }
        public Nullable<System.DateTime> FechaAtraque { get; set; }
        public Nullable<System.DateTime> FechaDesatraque { get; set; }
        public Nullable<bool> AfectoDetraccion { get; set; }
        public string TransaccionHelm { get; set; }
        public Nullable<long> IdPuerto { get; set; }
        public string NumeroDocumentoSolidario { get; set; }
        public string NombreNave2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoDetalle> DocumentoDetalle { get; set; }
    }
}
