//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numerador
    {
        public long IdNumerador { get; set; }
        public long Factura { get; set; }
        public long Boleta { get; set; }
        public long NotaCredito { get; set; }
        public long NotaDebito { get; set; }
        public long FacturaTalara { get; set; }
        public long BoletaTalara { get; set; }
        public long NotaCreditoTalara { get; set; }
        public long NotaDebitoTalara { get; set; }
        public long OrdenCompra { get; set; }
        public long OrdenCompraTalara { get; set; }
    }
}
