//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifaDetraccion
    {
        public long Id { get; set; }
        public string CodigoProducto { get; set; }
        public string NombreArticulo { get; set; }
        public string CodigoDetraccion { get; set; }
        public Nullable<int> PorcentajeDetraccion { get; set; }
        public Nullable<decimal> TopeMinimoSoles { get; set; }
        public Nullable<decimal> TopeMinimoDolares { get; set; }
        public string CentroBeneficio { get; set; }
    }
}
