//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_CORMVHIE
    {
        public string USR_CODEMP { get; set; }
        public string USR_MODFOR { get; set; }
        public string USR_CODCOM { get; set; }
        public int USR_NROFOR { get; set; }
        public string USR_CIRCOM { get; set; }
        public string USR_CIRAPL { get; set; }
        public string USR_SUCURS { get; set; }
        public Nullable<System.DateTime> USR_FCHMOV { get; set; }
        public string USR_NROCTA { get; set; }
        public string USR_DEPOSI { get; set; }
        public string USR_SECTOR { get; set; }
        public string USR_TEXTOS { get; set; }
        public string USR_SECPAG { get; set; }
        public string USR_SECREQ { get; set; }
        public string USR_CODLIS { get; set; }
        public Nullable<short> USR_ESTAUT { get; set; }
        public string USR_USRAUT { get; set; }
        public Nullable<System.DateTime> USR_FCHAUT { get; set; }
        public Nullable<decimal> USR_CAMSEC { get; set; }
        public string USR_TIPOPR { get; set; }
        public string USR_CODOPR { get; set; }
        public string USR_IDHELM { get; set; }
        public string USR_ESTDOC { get; set; }
        public Nullable<System.DateTime> USR_CO_FECALT { get; set; }
        public Nullable<System.DateTime> USR_CO_FECMOD { get; set; }
        public string USR_CO_USERID { get; set; }
        public string USR_CO_ULTOPR { get; set; }
        public string USR_CO_DEBAJA { get; set; }
        public string USR_CO_HORMOV { get; set; }
        public string USR_CO_MODULE { get; set; }
        public string USR_CO_OALIAS { get; set; }
        public byte[] USR_CO_TSTAMP { get; set; }
        public string USR_CO_LOTTRA { get; set; }
        public string USR_CO_LOTREC { get; set; }
        public string USR_CO_LOTORI { get; set; }
        public string USR_CO_SYSVER { get; set; }
        public string USR_CO_CMPVER { get; set; }
    }
}
