//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_CORMVIIE
    {
        public string USR_CORMVIIE_CODEMP { get; set; }
        public string USR_CORMVIIE_MODFOR { get; set; }
        public string USR_CORMVIIE_CODCOM { get; set; }
        public int USR_CORMVIIE_NROFOR { get; set; }
        public int USR_NROITM { get; set; }
        public string USR_IDHELMD { get; set; }
        public string USR_TIPPRO { get; set; }
        public string USR_ARTCOD { get; set; }
        public string USR_MODCPT { get; set; }
        public string USR_TIPCPT { get; set; }
        public string USR_CODCPT { get; set; }
        public Nullable<decimal> USR_CANTID { get; set; }
        public Nullable<decimal> USR_PRECIO { get; set; }
        public string USR_UNIMED { get; set; }
        public string USR_TIPUNI { get; set; }
        public Nullable<decimal> USR_PCTBF1 { get; set; }
        public string USR_TEXTOD { get; set; }
        public Nullable<decimal> USR_TOTLIN { get; set; }
        public string USR_CODDIM { get; set; }
        public string USR_CUENTA { get; set; }
        public Nullable<System.DateTime> USR_CO_FECALT { get; set; }
        public Nullable<System.DateTime> USR_CO_FECMOD { get; set; }
        public string USR_CO_USERID { get; set; }
        public string USR_CO_ULTOPR { get; set; }
        public string USR_CO_DEBAJA { get; set; }
        public string USR_CO_HORMOV { get; set; }
        public string USR_CO_MODULE { get; set; }
        public string USR_CO_OALIAS { get; set; }
        public byte[] USR_CO_TSTAMP { get; set; }
        public string USR_CO_LOTTRA { get; set; }
        public string USR_CO_LOTREC { get; set; }
        public string USR_CO_LOTORI { get; set; }
        public string USR_CO_SYSVER { get; set; }
        public string USR_CO_CMPVER { get; set; }
    }
}
