//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_FCRFAC
    {
        public string USR_CODEMP { get; set; }
        public string USR_MODFOR { get; set; }
        public string USR_CODFOR { get; set; }
        public int USR_NROFOR { get; set; }
        public string USR_CIRCOM { get; set; }
        public string USR_CIRAPL { get; set; }
        public string USR_MODCOM { get; set; }
        public string USR_CODCOM { get; set; }
        public string USR_SUCURS { get; set; }
        public string USR_NROCTA { get; set; }
        public Nullable<System.DateTime> USR_FCHMOV { get; set; }
        public string USR_CNDPAG { get; set; }
        public string USR_DEPOSI { get; set; }
        public string USR_SECTOR { get; set; }
        public string USR_CODLIS { get; set; }
        public string USR_TEXTOS { get; set; }
        public Nullable<decimal> USR_CAMSEC { get; set; }
        public string USR_TIPOPR { get; set; }
        public string USR_CODOPR { get; set; }
        public string USR_COMELE { get; set; }
        public string USR_OCCLIE { get; set; }
        public string USR_FETIOP { get; set; }
        public string USR_TIPORI { get; set; }
        public string USR_NROORI { get; set; }
        public Nullable<System.DateTime> USR_FECORI { get; set; }
        public Nullable<decimal> USR_IMBAAF { get; set; }
        public Nullable<decimal> USR_IMBAIN { get; set; }
        public Nullable<decimal> USR_IMBAEX { get; set; }
        public Nullable<decimal> USR_IMIMPU { get; set; }
        public Nullable<decimal> USR_IMTOTA { get; set; }
        public string USR_IDHELM { get; set; }
        public string USR_ESTDOC { get; set; }
        public string USR_MOTDEV { get; set; }
        public Nullable<System.DateTime> USR_FC_FECALT { get; set; }
        public Nullable<System.DateTime> USR_FC_FECMOD { get; set; }
        public string USR_FC_USERID { get; set; }
        public string USR_FC_ULTOPR { get; set; }
        public string USR_FC_DEBAJA { get; set; }
        public string USR_FC_HORMOV { get; set; }
        public string USR_FC_MODULE { get; set; }
        public string USR_FC_OALIAS { get; set; }
        public byte[] USR_FC_TSTAMP { get; set; }
        public string USR_FC_LOTTRA { get; set; }
        public string USR_FC_LOTREC { get; set; }
        public string USR_FC_LOTORI { get; set; }
        public string USR_FC_SYSVER { get; set; }
        public string USR_FC_CMPVER { get; set; }
        public string USR_CODACT { get; set; }
        public string USR_NROSUB { get; set; }
        public string USR_DENAVE { get; set; }
        public Nullable<int> USR_PUERTO { get; set; }
    }
}
