//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_FCRFAI
    {
        public string USR_FCRFAI_CODEMP { get; set; }
        public string USR_FCRFAI_MODFOR { get; set; }
        public string USR_FCRFAI_CODFOR { get; set; }
        public int USR_FCRFAI_NROFOR { get; set; }
        public int USR_NROITM { get; set; }
        public string USR_TIPPRO { get; set; }
        public string USR_ARTCOD { get; set; }
        public string USR_MODCPT { get; set; }
        public string USR_TIPCPT { get; set; }
        public string USR_CODCPT { get; set; }
        public Nullable<decimal> USR_PRECIO { get; set; }
        public Nullable<decimal> USR_CANTID { get; set; }
        public Nullable<decimal> USR_PCTBF1 { get; set; }
        public string USR_CODDIS { get; set; }
        public string USR_TEXTOD { get; set; }
        public string USR_IDHELM { get; set; }
        public Nullable<System.DateTime> USR_FC_FECALT { get; set; }
        public Nullable<System.DateTime> USR_FC_FECMOD { get; set; }
        public string USR_FC_USERID { get; set; }
        public string USR_FC_ULTOPR { get; set; }
        public string USR_FC_DEBAJA { get; set; }
        public string USR_FC_HORMOV { get; set; }
        public string USR_FC_MODULE { get; set; }
        public string USR_FC_OALIAS { get; set; }
        public byte[] USR_FC_TSTAMP { get; set; }
        public string USR_FC_LOTTRA { get; set; }
        public string USR_FC_LOTREC { get; set; }
        public string USR_FC_LOTORI { get; set; }
        public string USR_FC_SYSVER { get; set; }
        public string USR_FC_CMPVER { get; set; }
    }
}
